"""empty message

Revision ID: a077f1ca06c2
Revises: b397b448f7a2
Create Date: 2023-12-12 02:01:05.654923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a077f1ca06c2'
down_revision = 'b397b448f7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('journal',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('booktitle',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('booktitle',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('journal',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
