"""initial migration

Revision ID: b397b448f7a2
Revises: 
Create Date: 2023-12-12 01:58:50.996749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b397b448f7a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('citekey', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('journal', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('booktitle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('citekey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###
