"""first migration

Revision ID: d5de40bbd765
Revises: 
Create Date: 2023-12-12 18:24:13.638616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5de40bbd765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('citekey', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('booktitle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('citekey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###
